version: '3'


services:


  mysql:
    image: mysql:8.0.23
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ${PWD}/lakehouse/mysql/data/mysqldir:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      interval: 5s
      retries: 10
    ports:
      - 3306:3306
    networks:
      - oasiscorp
    hostname: mysql
  

# Jupyter Notebook - PySpark Enabled
  jupyter:
        image: 'jupyter/pyspark-notebook:spark-3.2.0'
        hostname: myjupyter
        container_name: jupyter
        networks:
            - oasiscorp
        ports:
          - "8888:8888"
        env_file:
          - .env
        volumes:
          - ${PWD}/lakehouse/jupyter/notebooks:/home/jovyan/work/notebooks/
          - ${PWD}/lakehouse/spark/resources/data:/home/jovyan/work/data/
          - ${PWD}/lakehouse/spark/jars:/home/jovyan/work/jars/
          - ${PWD}/lakehouse/spark/conf:/usr/local/spark/conf
          - ${PWD}/lakehouse/spark/sql:/usr/local/spark/sql/
        restart: always
  
  zeppelin:
    # image: apache/zeppelin:0.9.0
    image: 'spark-zep'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeppelin
    volumes:
      - ${PWD}/lakehouse/zeppelin/notebook:/notebook
      - ${PWD}/lakehouse/zeppelin/logs:/logs
      - ${PWD}/lakehouse/spark/resources/data:/learn
      # - ${SPARK_HOME}:/spark
      - ${PWD}/lakehouse/spark/conf:/spark/conf
      - ${PWD}/lakehouse/spark/jars:/spark/user_jars
      - ${PWD}/lakehouse/spark/sql/:/spark/sql/
    environment:
      # - SPARK_HOME=/spark
      - SPARK_SUBMIT_OPTIONS=--packages=org.mariadb.jdbc:mariadb-java-client:2.7.2 --jars=/spark/user_jars/mysql-connector-java-8.0.23.jar
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - ZEPPELIN_ADDR=0.0.0.0
      - ZEPPELIN_SPARK_MAXRESULT=10000
      - ZEPPELIN_INTERPRETER_OUTPUT_LIMIT=204800
      - ZEPPELIN_NOTEBOOK_COLLABORATIVE_MODE_ENABLE=false
    healthcheck:
      interval: 5s
      retries: 10
    ports:
      - 8080:8080
      - 4040:4040
      - 4041:4041
    networks:
      - oasiscorp
    hostname: "zeppelin"
    depends_on:
      - mysql

networks:
  oasiscorp:
    driver: bridge