version: '3'

services:

  # Postgres DB
  postgres:
    hostname: mypostgres
    container_name: postgres
    build:
      context: ./lakehouse/postgres
      dockerfile: Dockerfile
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./lakehouse/postgres/create_ranger_users.sql:/docker-entrypoint-initdb.d/create_ranger_users.sql
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always
    networks:
     - oasiscorp

  # Jupyter Notebook - PySpark Enabled
  jupyter:
        build:
            context: ./lakehouse/jupyter
        hostname: myjupyter
        container_name: jupyter
        networks:
            - oasiscorp
        ports:
          - "8888:8888"
        volumes:
          - ${PWD}/notebooks:/home/jovyan/work/notebooks/
          - ${PWD}/spark/resources/data:/home/jovyan/work/data/
          - ${PWD}/spark/resources/jars:/home/jovyan/work/jars/
          - ${PWD}/spark/conf:/usr/local/spark/conf
        restart: always

# Volumes 
volumes:
  postgres-db-volume:

networks:
  oasiscorp:
    driver: bridge