version: '3'

services:

  zeppelin:
    build:
            context: ./lakehouse/zepplin
    container_name: zeppelin
    volumes:
      - ${PWD}/lakehouse/zepplin/notebook:/notebook
      - ${PWD}/logs:/logs
      - ${PWD}/lakehouse/spark/resources/data:/learn
      # - ${SPARK_HOME}:/spark
    environment:
      # - SPARK_HOME=/spark
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - ZEPPELIN_ADDR=0.0.0.0
      - ZEPPELIN_SPARK_MAXRESULT=10000
      - ZEPPELIN_INTERPRETER_OUTPUT_LIMIT=204800
    healthcheck:
      interval: 5s
      retries: 10
    ports:
      - 8089:8080
    networks:
      - oasiscorp
    hostname: "zeppelin"



# Jupyter Notebook - PySpark Enabled
  jupyter:
        build:
            context: ./lakehouse/jupyter
        hostname: myjupyter
        container_name: jupyter
        networks:
            - oasiscorp
        ports:
          - "8888:8888"
        volumes:

          - ${PWD}/lakehouse/jupyter/notebooks:/home/jovyan/work/notebooks/
          - ${PWD}/lakehouse/spark/resources/data:/home/jovyan/work/data/
          - ${PWD}/lakehouse/spark/resources/jars:/home/jovyan/work/jars/
          - ${PWD}/lakehouse/spark/conf:/usr/local/spark/conf
          - ${PWD}/lakehouse/spark/sql:/usr/local/spark/sql/
        restart: always


           

volumes:
  postgres-db-volume:


networks:
  oasiscorp:
    driver: bridge