version: '3'
services:

  # Jupyter Notebook - PySpark Enabled
  jupyter-spark:
        build:
            context: jupyter
        hostname: myjupyter
        container_name: jupyter_container
        networks:
            - oasiscorp
        ports:
          - "8888:8888"
        volumes:
          - ./jupyter/notebooks:/home/jovyan/work/notebooks/
          - ./spark/resources/data:/home/jovyan/work/data/
          - ./spark/resources/jars:/home/jovyan/work/jars/
          - ./spark/conf:/usr/local/spark/conf
        restart: always
        depends_on:
          - mysql

networks:
  oasiscorp:
    driver: bridge