version: '3'

services:

  # Postgres DB
  postgres:
    hostname: oasispostgres
    container_name: postgres_container
    build:
      context: ./lakehouse/postgres
      dockerfile: Dockerfile
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./lakehouse/postgres/create_ranger_users.sql:/docker-entrypoint-initdb.d/create_ranger_users.sql
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always
    networks:
     - oasiscorp

# Namenode: HDFS
  namenode:
      image: dimeji/hadoop-namenode:latest
      container_name: hadoop-namenode
      volumes:
        - namenode:/hadoop/dfs/name
      environment:
        - CLUSTER_NAME=test
      env_file:
        - ${PWD}/hadoop-hive.env
      ports:
        - "50070:50070"
      networks:
        - oasiscorp

  # Datanode: HDFS      
  datanode:
      image: dimeji/hadoop-datanode:latest
      container_name: hadoop-datanode
      volumes:
        - datanode:/hadoop/dfs/data
      env_file:
        - ${PWD}/hadoop-hive.env
      environment:
        SERVICE_PRECONDITION: "namenode:50070"
      ports:
        - "50075:50075"
      depends_on:
      - namenode
      networks:
        - oasiscorp

  # Hive: A Hive Metastore and a Hive Metastore Server
  hive:
      image: dimeji/hive-metastore
      hostname: hive
      container_name: hive-metastore
      env_file:
        - ${PWD}/hadoop-hive.env
      command: /opt/hive/bin/hive --service metastore
      environment:
        SERVICE_PRECONDITION: "namenode:50070 datanode:50075 oasispostgres:5432"
      ports:
        - "9083:9083"
      depends_on:
        - namenode
        - datanode
      networks:
        - oasiscorp
      restart: on-failure

      # /opt/hive/conf

  # Hive Server: A Hive Metastore and a Hive Metastore Server    
  hive-server:
      image: dimeji/hive-server
      container_name: hive-server
      env_file:
        - ${PWD}/hadoop-hive.env
      environment:
        HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive/metastore"
        SERVICE_PRECONDITION: "hive:9083"
      ports:
        - "10000:10000"
      depends_on:
        - hive
      networks:
        - oasiscorp


  # Jupyter notebook
  jupyter-spark:
        hostname: myjupyter
        container_name: jupyter_container
        image: 'jupyter/pyspark-notebook:spark-3.2.0'
        networks:
            - oasiscorp
        ports:
          - "8888:8888"
        volumes:
          - ./notebooks:/home/jovyan/work/notebooks/
          - ./spark/resources/data:/home/jovyan/work/data/
          - ./spark/resources/jars:/home/jovyan/work/jars/
          - ./spark/conf:/usr/local/spark/conf
        restart: always
        depends_on:
                - postgres



          

# Volumes 
volumes:
  postgres-db-volume:
  namenode:
  datanode:

networks:
  oasiscorp:
    driver: bridge